name: tappglobalapp
description: "A digital business card application that revolutionizes networking through smart lead management and seamless contact sharing."
publish_to: 'none'

version: 1.0.0+1

environment:
 sdk: '>=3.0.0 <4.0.0'

dependencies:
 flutter:
   sdk: flutter
 cupertino_icons: ^1.0.8
 firebase_auth: ^5.3.4
 google_sign_in: ^6.2.2
 sign_in_with_apple: ^6.1.4
 logger: ^2.5.0
 firebase_core: ^3.9.0
 cloud_firestore: ^5.6.0
 font_awesome_flutter: ^10.8.0
 url_launcher: ^6.3.1
 google_fonts: ^6.2.1
 flutter_dotenv: ^5.2.1

dev_dependencies:
 flutter_test:
   sdk: flutter
 flutter_lints: ^5.0.0

flutter:
 uses-material-design: true
 assets:
   - assets/logo/logo_black.png
   - assets/logo/logo_white.png